ella_padre(ignacio, teresa).
ella_padre(ignacio, hugo).
ella_padre(ignacio, daniel).
ella_padre(ignacio, dolores).
ella_padre(ignacio, claudia).
ella_padre(ignacio, martin).
ella_padre(ignacio, raymundo).
ella_padre(ignacio, vianey).
ella_madre(rosario, teresa).
ella_madre(rosario, hugo).
ella_madre(rosario, daniel).
ella_madre(rosario, dolores).
ella_madre(rosario, claudia).
ella_madre(rosario, martin).
ella_madre(rosario, raymundo).
ella_madre(rosario, vianey).
el_padre(manuel, edith).
el_padre(manuel, carlos).
el_padre(manuel, rene).
el_padre(manuel, samuel).
el_padre(manuel, nelson).
el_madre(salvadora, edith).
el_madre(salvadora, carlos).
el_madre(salvadora, rene).
el_madre(salvadora, samuel).
el_madre(salvadora, nelson).
padre(nelson, victor).
padre(nelson, glorybell).
padre(nelson, valeria).
madre(teresa, victor).
madre(teresa, glorybell).
madre(teresa, valeria).

